-- =====================================================================
-- CORREÇÃO ESTRUTURAL: liga o login (Supabase Auth, sempre uuid) à
-- tabela `artistas` (id sempre integer, sem auto-incremento).
-- =====================================================================

-- 0) Corrige (ou cria, se ainda não existir) a tabela documentos_gerados.
-- Ela tinha sido criada com artista_id como uuid — errado, já que
-- artistas.id é integer.
create table if not exists public.documentos_gerados (
  id uuid primary key default gen_random_uuid(),
  artista_id integer not null references public.artistas(id) on delete cascade,
  tipo text not null,
  arquivo text not null,
  criado_em timestamptz not null default now()
);

-- Se a tabela já existia com artista_id no tipo errado (uuid), corrige:
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'documentos_gerados'
      and column_name = 'artista_id' and data_type = 'uuid'
  ) then
    alter table public.documentos_gerados drop constraint if exists documentos_gerados_artista_id_fkey;
    alter table public.documentos_gerados alter column artista_id type integer using null;
    alter table public.documentos_gerados add constraint documentos_gerados_artista_id_fkey
      foreign key (artista_id) references public.artistas(id) on delete cascade;
  end if;
end $$;

alter table public.documentos_gerados enable row level security;

-- 1) Liga cada artista ao seu usuário de login.
alter table public.artistas
  add column if not exists auth_user_id uuid unique references auth.users(id);

comment on column public.artistas.auth_user_id is
  'UUID do usuário no Supabase Auth (auth.uid()) — é isso, e não artistas.id, que identifica quem está logado.';

-- 2) Faz artistas.id gerar sozinho a partir de agora (BY DEFAULT, não
-- ALWAYS — permite inserir um id manual se algum processo antigo ainda
-- precisar, mas por padrão gera automaticamente).
-- Envolvido em DO $$ ... $$ para ser seguro rodar de novo: se a coluna
-- já for identity (ex.: script já executado antes, ou tabela criada
-- assim desde o início), o ALTER original dá erro 55000 e interrompe o
-- script inteiro — aqui ele é apenas ignorado nesse caso.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'artistas'
      and column_name = 'id' and is_identity = 'YES'
  ) then
    alter table public.artistas alter column id add generated by default as identity;
  end if;
end $$;

-- Garante que a próxima geração comece depois do maior id já existente
-- (necessário porque a coluna já tinha dados antes de virar identity).
select setval(
  pg_get_serial_sequence('artistas', 'id'),
  coalesce((select max(id) from public.artistas), 1)
);

-- 3) Recria a RLS de `artistas` usando auth_user_id 
drop policy if exists "artistas_le_proprio" on public.artistas;
create policy "artistas_le_proprio"
  on public.artistas for select
  using (auth.uid() = auth_user_id);

drop policy if exists "artistas_cria_proprio" on public.artistas;
create policy "artistas_cria_proprio"
  on public.artistas for insert
  with check (auth.uid() = auth_user_id);

drop policy if exists "artistas_atualiza_proprio" on public.artistas;
create policy "artistas_atualiza_proprio"
  on public.artistas for update
  using (auth.uid() = auth_user_id)
  with check (auth.uid() = auth_user_id);

-- 4) Recria a RLS de todas as tabelas que guardam artista_id (integer).
-- O padrão agora é sempre: "o artista_id desta linha pertence a um
-- artistas.id cujo auth_user_id é o usuário logado".

-- shows
drop policy if exists "shows_artista_le_proprio" on public.shows;
create policy "shows_artista_le_proprio"
  on public.shows for select
  using (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

drop policy if exists "shows_artista_cria_proprio" on public.shows;
create policy "shows_artista_cria_proprio"
  on public.shows for insert
  with check (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

-- transacoes_financeiras
drop policy if exists "transacoes_artista_le_proprio" on public.transacoes_financeiras;
create policy "transacoes_artista_le_proprio"
  on public.transacoes_financeiras for select
  using (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

-- O artista nunca deve poder criar/editar as próprias transações
-- financeiras
drop policy if exists "transacoes_artista_cria_proprio" on public.transacoes_financeiras;

-- contratos
drop policy if exists "contratos_artista_le_proprio" on public.contratos;
create policy "contratos_artista_le_proprio"
  on public.contratos for select
  using (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

drop policy if exists "contratos_artista_assina_proprio" on public.contratos;
create policy "contratos_artista_assina_proprio"
  on public.contratos for update
  using (artista_id in (select id from public.artistas where auth_user_id = auth.uid()))
  with check (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

-- Faltava: contratos precisa de policy de INSERT 
drop policy if exists "contratos_artista_cria_proprio" on public.contratos;
create policy "contratos_artista_cria_proprio"
  on public.contratos for insert
  with check (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

-- obras
drop policy if exists "obras_artista_le_proprio" on public.obras;
create policy "obras_artista_le_proprio"
  on public.obras for select
  using (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

drop policy if exists "obras_artista_cria_proprio" on public.obras;
create policy "obras_artista_cria_proprio"
  on public.obras for insert
  with check (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

drop policy if exists "obras_artista_atualiza_proprio" on public.obras;
create policy "obras_artista_atualiza_proprio"
  on public.obras for update
  using (artista_id in (select id from public.artistas where auth_user_id = auth.uid()))
  with check (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

drop policy if exists "obras_artista_deleta_proprio" on public.obras;
create policy "obras_artista_deleta_proprio"
  on public.obras for delete
  using (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

-- compositores 
drop policy if exists "compositores_artista_le_proprio" on public.compositores;
create policy "compositores_artista_le_proprio"
  on public.compositores for select
  using (
    obra_id in (
      select o.id from public.obras o
      join public.artistas a on a.id = o.artista_id
      where a.auth_user_id = auth.uid()
    )
  );

drop policy if exists "compositores_artista_cria_proprio" on public.compositores;
create policy "compositores_artista_cria_proprio"
  on public.compositores for insert
  with check (
    obra_id in (
      select o.id from public.obras o
      join public.artistas a on a.id = o.artista_id
      where a.auth_user_id = auth.uid()
    )
  );

-- documentos_gerados 
drop policy if exists "documentos_gerados_artista_le_proprio" on public.documentos_gerados;
create policy "documentos_gerados_artista_le_proprio"
  on public.documentos_gerados for select
  using (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));

drop policy if exists "documentos_gerados_artista_cria_proprio" on public.documentos_gerados;
create policy "documentos_gerados_artista_cria_proprio"
  on public.documentos_gerados for insert
  with check (artista_id in (select id from public.artistas where auth_user_id = auth.uid()));
